version: 2
orbs:
  win: circleci/windows@2.2.0
jobs:
  build_12.18.2:
    docker:
      - image: 'circleci/node:12.18.2'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}'
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}'
      - run: npm test
  build_latest:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}'
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}'
      - run: npm test
workflows:
  version: 2
  workflow:
    jobs:
      - build_12.18.2
      - build_latest
